[package]
name = "polybench-reform"
version = "0.1.0"
authors = ["Takahiro Ueda <t.ueda.od@juntendo.ac.jp>"]
edition = "2018"

[dependencies]
reform = { git = "https://github.com/tueda/reform.git", branch = "fix-serialize" }
